repos:
-   repo: local
    hooks:
      -   id: black
          name: black
          entry: pipenv run black
          language: system
          types: [python]

      -   id: flake8
          name: Flake8
          entry: pipenv run flake8
          language: system
          types: [python]

