name: Auto-format and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development

jobs:
  autoformat-and-lint:
    name: Run autoformatting and linting on src folder
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install black flake8 pyproject-flake8==0.0.1a2

      - name: Run black
        run: make black

      - name: Run flake8
        run: make lint

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install pytest==7.1.2

      - name: Run tests
        run: make test
